apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.secret.data.DB_PASSWORD | quote }}
  JWT_SECRET: {{ .Values.secret.data.JWT_SECRET | quote }}
